services:
  dev:
    container_name: dev-rest-framework
    build: docker/dev
    volumes:
      - .:/workspaces
  web-server:
    build: docker/web-server
    container_name: web-server-rest-framework
    ports:
      - "80:80"
    volumes:
      - ./docker/web-server/files:/app
      - ./src:/app/src
      - ./vendor:/app/vendor
